# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lochat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lochat
pod ‘Firebase/Core’
pod 'RealmSwift'
pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.7'

  target 'lochatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lochatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
